### PR TITLE
updated scripts to work with large number of users

### LINKED ISSUE #101: Create public keys in chunk
Since we are working with 100k users we need to submit the pubkeys in chunks to the ethereum chain.

### PR DESCRIPTION
**Pull request by vaibhavchellani**
Fixes #101 and #102 and also updates the gov variable to match the deployment scale.

### CODE REVIEW

**Comment by vaibhavchellani** [comment]
Fixing CI..

**Comment by ChihChengLiang** [comment]
Is this blocked?

**Comment by vaibhavchellani** [comment]
Yeah trying to fix the issue due to which the CI is failing. This is a little bit low priority for me at the moment, will fix it as soon as possible.

**Comment by vaibhavchellani** [comment]
yeah im going to remove that from the commit, Ill send it to you separately, the command to produce that is on the node.

**Pull request merged**
